app:
    jwtExpirationMs: 60000000
    jwtSecret: ${JWT_SECRET_KEY}
    dataLoader: true
cloudinary:
    apiKey: 548943318855874
    apiSecret: ${CLOUDINARY_API_SECRET}
    cloudName: djog8qqis
server:
    port: 8084
#logging:
#    level:
#        root: debug
spring:
    data:
        web:
            pageable:
                one-indexed-parameters: true
#                max-page-size: 100
#                default-page-size: 20
    datasource:
        driverClassName: org.postgresql.Driver
#        password: ${DB_PASSWORD}
#        url: ${DB_URL} #jdbc:postgresql://localhost:5432/reddit
#        username: ${DB_USER} #compose-postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                show_sql: false
        open-in-view: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
springdoc:
    packagesToScan: com.beval.server.api.v1
    pathsToMatch: /api/v1/**
    swagger-ui:
        operationsSorter: method
        tagsSorter: alpha
management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus
