app:
    jwtExpirationMs: 60000000
    jwtSecret: ${JWT_SECRET_KEY}
server:
    port: 8084
#logging:
#    level:
#        root: debug
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${DB_PASSWORD}
        url: jdbc:mysql://localhost:3306/reddit?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                show_sql: false
        open-in-view: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
