app:
    jwtExpirationMs: 60000000
    jwtSecret: 6jCTFSacGgVfffoK/c/DQg4z0848R9a71acEiKgjozs=
server:
    port: 8084
spring:
    data:
        rest:
            base-path: /api
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: meuhas12emili
        url: jdbc:mysql://localhost:3306/reddit?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
